# 参考资料

- 【好】<https://www.cnblogs.com/feichengwulai/articles/3793261.html>
- [看完这篇Exception 和 Error，和面试官扯皮就没问题了](<https://mp.weixin.qq.com/s?__biz=MzU2NDg0OTgyMA==&mid=2247486149&idx=1&sn=fe3ab875ae081bfc47166b68ba2d4bc9&chksm=fc45f736cb327e20ea9c62a6f2aa88928b6666d9cc868ab378a41886417e445faef269017996&mpshare=1&scene=23&srcid=&sharer_sharetime=1586344294086&sharer_shareid=e6d90aec84add5cf004cb1ab6979727c#rd>)



# [在方法内部throw异常，必须要同时在方法头部声明throws吗？](https://segmentfault.com/q/1010000012438163)

java异常一般分为`Checked`异常和`Runtime`异常，所有`RuntimeException`类及其子类的实例被称为`Runtime`异常，不属于该范畴的异常则被称为`CheckedException`。
Java认为`Checked`异常都是可以被处理的异常，所以Java程序必须显示处理Checked异常。如果程序没有处理`Checked`异常，该程序在编译时就会发生错误无法编译。
而`RuntimeException`异常如果没有显示的捕获处理则由系统自动检测并将它们交给缺省的异常处理程序。
`JSONException`应该是`RuntimeException`的子类，可以不用显式的对它try...catch或者throws.如果没有对该异常的处理会交给jvm处理。
而你自己写的异常肯定是属于Checked异常，被认为是可以避免的异常，必须**①try...catch**或者**②显式的抛出throws**不然编译报错。如果你自定义的异常想像`throw new JSONException`这样处理，则你自定义的异常需要继承`RuntimeException`即可。

=================================以下理解重点=========================================

3.首先方法后边加上throws Exception的作用是抛出异常。其中Exception可以理解为所有异常，也可以抛出指定异常。如果方法后边不加throws Exception，方法出了异常就会向上传递抛出(**如果方法有调用者，那就交给调用者处理，如果调用者继续一层层抛出，最终交给虚拟机，虚拟机处理，整个程序会中断！ 如果在程序中捕获  还可以继续进行。**)。

4，**如果有异常你不用层层向上抛出那么你就要用throws Exception**，然后在调用时加上try catch语句处理...。。。如果有异常我一般选择这种处理方法。相比不用throws Exception，加上了throws Exception后，调用该方法时，必须加上try...catch才可以(你加上throw exception。调用的地方就必须try catch，不然编译都不过。。这样代码就更健壮了。)。

　　相当于一种约束，如果不加throws Exception，在多个地方调用方法时，添加try...catch也可以，但是有时候就会忘记加try...catch。

5，另外异常处理的原则是尽可能早的catch异常，**正常的程序不应该写throws Exception**。

6，运行异常（继承RuntimeException）可以不捕获，向上抛，如果一直没有处理，则jvm会自动处理（停止线程，打印异常）。
---非运行期异常，必须捕获或者在方法声明。

======================================================================================

## [32 Java 中的异常处理](https://snailclimb.gitee.io/javaguide/#/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86?id=32-java-%e4%b8%ad%e7%9a%84%e5%bc%82%e5%b8%b8%e5%a4%84%e7%90%86)

### [Java 异常类层次结构图](https://snailclimb.gitee.io/javaguide/#/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86?id=java-%e5%bc%82%e5%b8%b8%e7%b1%bb%e5%b1%82%e6%ac%a1%e7%bb%93%e6%9e%84%e5%9b%be)

![Java异常类层次结构图](https://my-blog-to-use.oss-cn-beijing.aliyuncs.com/2019-2/Exception.png)

在 Java 中，所有的异常都有一个共同的祖先 java.lang 包中的 **Throwable 类**。Throwable： 有两个重要的子类：**Exception（异常）** 和 **Error（错误）** ，二者都是 Java 异常处理的重要子类，各自都包含大量子类。

**Error（错误）:是程序无法处理的错误**，表示运行应用程序中较严重问题。大多数错误与代码编写者执行的操作无关，而表示代码运行时 JVM（Java 虚拟机）出现的问题。例如，Java 虚拟机运行错误（Virtual MachineError），当 JVM 不再有继续执行操作所需的内存资源时，将出现 OutOfMemoryError。这些异常发生时，Java 虚拟机（JVM）一般会选择线程终止。

这些错误表示故障发生于虚拟机自身、或者发生在虚拟机试图执行应用时，如 Java 虚拟机运行错误（Virtual MachineError）、类定义错误（NoClassDefFoundError）等。这些错误是不可查的，因为它们在应用程序的控制和处理能力之 外，而且绝大多数是程序运行时不允许出现的状况。对于设计合理的应用程序来说，即使确实发生了错误，本质上也不应该试图去处理它所引起的异常状况。在 Java 中，错误通过 Error 的子类描述。

**Exception（异常）:是程序本身可以处理的异常**。Exception 类有一个重要的子类 **RuntimeException**。RuntimeException 异常由 Java 虚拟机抛出。**NullPointerException**（要访问的变量没有引用任何对象时，抛出该异常）、**ArithmeticException**（算术运算异常，一个整数除以 0 时，抛出该异常）和 **ArrayIndexOutOfBoundsException** （下标越界异常）。

**注意：异常和错误的区别：异常能被程序本身处理，错误是无法处理。**

### [Throwable 类常用方法](https://snailclimb.gitee.io/javaguide/#/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86?id=throwable-%e7%b1%bb%e5%b8%b8%e7%94%a8%e6%96%b9%e6%b3%95)

- **public string getMessage()**:返回异常发生时的简要描述
- **public string toString()**:返回异常发生时的详细信息
- **public string getLocalizedMessage()**:返回异常对象的本地化信息。使用 Throwable 的子类覆盖这个方法，可以生成本地化信息。如果子类没有覆盖该方法，则该方法返回的信息与 getMessage（）返回的结果相同
- **public void printStackTrace()**:在控制台上打印 Throwable 对象封装的异常信息

### [异常处理总结](https://snailclimb.gitee.io/javaguide/#/docs/java/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86?id=%e5%bc%82%e5%b8%b8%e5%a4%84%e7%90%86%e6%80%bb%e7%bb%93)

- **try 块：** 用于捕获异常。其后可接零个或多个 catch 块，如果没有 catch 块，则必须跟一个 finally 块。
- **catch 块：** 用于处理 try 捕获到的异常。
- **finally 块：** 无论是否捕获或处理异常，finally 块里的语句都会被执行。当在 try 块或 catch 块中遇到 return 语句时，finally 语句块将在方法返回之前被执行。

**在以下 4 种特殊情况下，finally 块不会被执行：**

1. 在 finally 语句块第一行发生了异常。 因为在其他行，finally 块还是会得到执行
2. 在前面的代码中用了 System.exit(int)已退出程序。 exit 是带参函数 ；若该语句在异常语句之后，finally 会执行
3. 程序所在的线程死亡。
4. 关闭 CPU。

下面这部分内容来自 issue:<https://github.com/Snailclimb/JavaGuide/issues/190>。

**注意：** 当 try 语句和 finally 语句中都有 return 语句时，在方法返回之前，finally 语句的内容将被执行，并且 finally 语句的返回值将会覆盖原始的返回值。如下：

```java
    public static int f(int value) {
        try {
            return value * value;
        } finally {
            if (value == 2) {
                return 0;
            }
        }
    }Copy to clipboardErrorCopied
```

如果调用 `f(2)`，返回值将是 0，因为 finally 语句的返回值覆盖了 try 语句块的返回值。